In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("multiple_linear_regression_dataset.csv", sep=";")

In [4]:
df

deneyim   maas  yas
0       0.5   2500   22
1       0.0   2250   21
2       1.0   2750   23
3       5.0   8000   25
4       8.0   9000   28
5       4.0   6900   23
6      15.0  20000   35
7       7.0   8500   29
8       3.0   6000   22
9       2.0   3500   23
10     12.0  15000   32
11     10.0  13000   30
12     14.0  18000   34
13      6.0   7500   27

In [5]:
from sklearn.linear_model import LinearRegression

In [6]:
mul_linear_reg = LinearRegression()

In [7]:
x = df.iloc[:,[0,2]].values
y = df.maas.values.reshape(-1, 1)

In [8]:
mul_linear_reg.fit(x,y)

LinearRegression()

In [9]:
mul_linear_reg.intercept_

array([10376.62747228])

In [10]:
mul_linear_reg.coef_

array([[1525.50072054, -416.72218625]])

In [11]:
mul_linear_reg.predict(np.array([[10, 35], [5,35]]))

array([[11046.35815877],
       [ 3418.85455609]])